version: '3'

services:
  parkhere-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL__PASSWORD}
      - MSSQL_PID=${SQL__PID}
      - TZ=Europe/Sarajevo
    ports:
      - "1401:1433"
    expose:
      - 1433
    networks:
      - parkhere-2025
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SQL__PASSWORD} -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
      - TZ=Europe/Sarajevo
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - parkhere-2025

  parkhere-rabbitmq:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.notifications
    environment:
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
      - TZ=Europe/Sarajevo
    depends_on:
      rabbitmq:
        condition: service_started
      parkhere-sql:
        condition: service_healthy
      parkhere-api:
        condition: service_started
    networks:
      - parkhere-2025
    ports:
      - 7111:80
  
  parkhere-api:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=parkhere-sql,1433;Database=${SQL__DATABASE};User Id=${SQL__USER};Password=${SQL__PASSWORD};ConnectRetryCount=5;TrustServerCertificate=True;
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ_VIRTUALHOST=/
      - TZ=Europe/Sarajevo
    ports:
      - "5130:5130"
    networks:
      - parkhere-2025
    depends_on:
      parkhere-sql:
        condition: service_healthy

networks:
  parkhere-2025:
    driver: bridge